// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

// 变更流水表
type TCpRunningBillEsim struct {
	// 主键流水号
	ID     int64          `json:"id"`
	Iccid  string         `json:"iccid"`
	Imsi   string         `json:"imsi"`
	Msisdn string         `json:"msisdn"`
	Json   sql.NullString `json:"json"`
	// 创建时间
	CreateTime sql.NullTime `json:"create_time"`
	// 0  失败 1成功
	Status sql.NullString `json:"status"`
	// 生效时间
	EffectiveTime sql.NullTime `json:"effective_time"`
}

// 客户SIM卡表
type TCpSim struct {
	// 主键
	ID string `json:"id"`
	// 客户id
	CustomerID int64 `json:"customer_id"`
	// 运营商ID
	OperatorID sql.NullInt64 `json:"operator_id"`
	ClientID   string        `json:"client_id"`
	// sim卡唯一识别码
	Iccid string `json:"iccid"`
	// 网络标识码
	Imsi string `json:"imsi"`
	// 网络SDN
	Msisdn string `json:"msisdn"`
	// SIM状态 1：未生效；2：可测试；3：库存；4：激活；5：停卡
	Status int32 `json:"status"`
	// 启用禁用状态1是启用  2是禁用  默认启用
	AbleStatus sql.NullInt32 `json:"able_status"`
	// 是否删除 0：否；1：是
	IsDelete bool `json:"is_delete"`
	// 创建时间
	CreateTime time.Time `json:"create_time"`
	// 更新时间
	UpdateTime sql.NullTime `json:"update_time"`
	// 推送状态；1：未推送，2：已推送，3：推送失败
	PushStatus int32 `json:"push_status"`
	// sim卡推送时间
	PushTime sql.NullTime `json:"push_time"`
	// xinbaID
	SimbaID sql.NullInt64 `json:"simba_id"`
	// 首次激活时间
	FirstActivateTime sql.NullTime `json:"first_activate_time"`
	// 是否异常 1 否 2 是
	IsAbnormal sql.NullInt32 `json:"is_abnormal"`
	// 异常内容
	Contents sql.NullString `json:"contents"`
	// 生效时间
	EffectiveTime sql.NullTime `json:"effective_time"`
}
