app:
  name: 'op-mno'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5070

logger:
  log_level: 'debug'
  rollbar_env: 'op-mno'



client:
  connect_client_url: cp-connect-svc:4000


mysql:
  pool_max: 100
  idle_conn_max: 50
  max_idle_time: 86400
  dsn_url: root:Simba123!@#@tcp(mysql8:3306)/connect_cp?charset=utf8&parseTime=True&loc=Local